# Generated by Django 2.2.16 on 2023-02-25 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_follow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'verbose_name': 'Подписаться на автора', 'verbose_name_plural': 'Подписки'},
        ),
    ]
